### ISSUE TITLE
Boundary without a space

### ISSUE THREAD

**Issue by ml-pickle** [fnl/segtok#14]
A common typo is omitting a space between sentences.

`I couldn't believe it.We should have left early.`

Is this something segtok is supposed to catch?

**Comment by fnl** [comment]
No, segtok cannot handle such cases, as that would break valid cases that should not split, and segtok does no linguistic or statistic analyses, opting to be fast and simple. If you want such cases to split, and have noisy text, you might just preprocess the input, adding a space in such cases. Then segtok will split the valid cases and leave non-terminals joined (in most cases, at least...)
