### ISSUE TITLE
Issue with sentence separator

### ISSUE THREAD

**Issue by arcticOak2** [fnl/segtok#17]
Input: I liked the book he sent.The book was good
Output: ['I liked the book he sent.The book was good']

**Comment by fnl** [comment]
On Fri, Sep 7, 2018, at 11:39, Abhijeet Kumar wrote:
> Input: I liked the book he sent.The book was good
> Output: ['I liked the book he sent.The book was good']

This pattern cannot easily be covered without first detecting words, and
cleaning up poor text.

**Comment by arcticOak2** [comment]
Okay so, you are saying that before sending input I need to clean my texts?

**Comment by fnl** [comment]
Either that or play around with the pattern and see if not requiring space(s) between sentences would work (read: unit tests don't break), after all; Any PR most welcome! 

That said, I'm working on a new version (2) of this tool in my spare time, that will do tokenization first, and does segmenting only thereafter. That will mean it avoids the issue and has no problems segmenting sentences like the one you posted.

But as my spare time is rather limited with my many  roles these days, I am sure looking into the current setup and making a PR would be the fastest way if this is an urgent matter for you. Thank you for reporting, in any case!

**Comment by fnl** [comment]
Hi @arcticOak2 - this is fixed, now - but in v2 of segtok, code-named syntok: https://github.com/fnl/syntok

I don't think I will add a fix for this to segtok, though (and will probably start moving on to supporting syntok rather than segtok), so I'm closing this ticket.
But I'd love to hear from you about syntok!
