### ISSUE TITLE
Date gets segmented

### ISSUE THREAD

**Issue by mnishant2** [fnl/segtok#19]
While using this tokenizer dates get segmented,as in if my sentence contains date in the format DD/MM/YYYY, it gets tokenized as DD / MM / YYYY.
How to work around this issue?

**Comment by fnl** [comment]
Can you be more specific why that is a problem, i.e., what problem you are trying to solve, please?

**Comment by mnishant2** [comment]
I am working on entity recognition and I want to extract dates, thus it would be great if the whole date could be considered one single token.

**Comment by fnl** [comment]
In that case, I could suggest you create a new tokenizer on top of the existing ones that does not split on the pattern. E.g.:

```python
from segtok.tokenizer import _matches, word_tokenizer, unescape

@_matches(r"""\b(
      [0-9]{1,2}  # day or month
      \/
      [0-9]{1,2}  # day or month
      \/
     [12][0-9]{3} # years 1000-2999
    )\b""")
def date_tokenizer(sentence):
    return [token for i, span in enumerate(date_tokenizer.split(sentence))
            for token in ((span,) if i % 2 else word_tokenizer(unescape(span)))]
```

If you run that in a console, I get:

```
In [4]: date_tokenizer("Today is 10/11/2019.")
Out[4]: ['Today', 'is', '10/11/2019', '.']
```

If this feature/function has more segtok users +1'ing it, I am happy to add it; But for now, please just create your own, as it is pretty trivial to add on your own.

**Comment by mnishant2** [comment]
@fnl  thanks for the prompt resolution. I managed to do the needful with slight regex tinkering, but yours is definitely the more efficient solution
