### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [fnl/segtok#23]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
find . -iname '*.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./segtok/segmenter.py:48: DeprecationWarning: invalid escape sequence \.
  ABBREVIATIONS = """
```

**Comment by fnl** [comment]
PR merged and released in v1.5.10; Thanks, @tirkarthi
