### ISSUE TITLE
Currency and percentages

### ISSUE THREAD

**Issue by dineshbvadhia** [fnl/segtok#5]
Ran the simple

> segmenter data | tokenizer

and noticed that currency values split from the currency symbol eg. $4.12 -> $ 4.12. Similarly for percentages eg. %7.1 -> % 7.1.

**Comment by fnl** [comment]
Yes, and that's what you would expect from a correct tokenizer. Check the
Penn PoS tags, this tokenization strategy is the de facto standard.

Florian

**Comment by fnl** [comment]
[Penn PoS tags](http://www.comp.leeds.ac.uk/amalgam/tagsets/upenn.html) define tokens by numbers with the tag CD, symbol tokens are tagged SYM for things like percentages, $ is used for currency tokens/symbols, and so forth.

In other words, the current behavior of `segtok` is the _correct_ one and I am therefore closing this issue.
