### ISSUE TITLE
tokenizer usage

### ISSUE THREAD

**Issue by dineshbvadhia** [fnl/segtok#7]
Have read the documentation at http://fnl.es/segtok-a-segmentation-and-tokenization-library.html but unclear about the tokenization pipeline. Segtok is being used within a program, simply as:

```
tokens = web_tokenizer(sentence)
```

The web_tokenizer calls word_tokenizer which calls space_tokenizer. However, not found a call to symbol_tokenizer.  Is that right or did I miss something?

**Comment by fnl** [comment]
That is correct as far as I can tell by re-reading the code myself.

However, please do not abuse the bug and issue tracker for asking questions and rather contact me directly.
